language: node_js
node_js:
  - "stable"
  - "4.1"
  - "4.0"

notifications:
    email: false

sudo: false

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
